import argparse
import json
import os
import sys
from datetime import datetime


def generate_report(analysis_json: str, output_dir: str = "reports") -> str:
    """Generate a markdown security report from analyze-audio JSON output."""
    try:
        data = json.loads(analysis_json)
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Invalid JSON input: {e}"}))
        sys.exit(1)

    if "error" in data:
        print(json.dumps({"error": data["error"]}))
        sys.exit(1)

    # Extract fields
    filepath = data.get("file", "unknown")
    filename = os.path.basename(filepath)
    score = data.get("score", 0)
    confidence = data.get("confidence", 0)
    duration = data.get("duration_seconds", "N/A")
    sample_rate = data.get("sample_rate", "N/A")
    features = data.get("features", {})
    analyzer = data.get("analyzer", "unknown")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Classification logic (mirrors SKILL.md rules)
    if confidence < 60:
        label = "UNCERTAIN"
        action = "⚠️ Manual review recommended — confidence too low for definitive classification."
        badge = "🟡"
    elif score <= 40:
        label = "AUTHENTIC"
        action = "✅ No action needed — audio appears to be genuine."
        badge = "🟢"
    elif score <= 69:
        label = "UNCERTAIN"
        action = "⚠️ Manual review recommended — audio shows some synthetic markers."
        badge = "🟡"
    else:
        label = "DEEPFAKE"
        action = "🚨 BLOCK IMMEDIATELY — Escalate to security team. Do not use this audio."
        badge = "🔴"

    # Build feature table rows
    feature_rows = "\n".join(
        f"| {k.replace('_', ' ').title()} | `{v}` |"
        for k, v in features.items()
    )

    # Build markdown report
    report_name = f"report_{os.path.splitext(filename)[0]}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path = os.path.join(output_dir, report_name)

    report_md = f"""# 🛡️ AudioGuard Security Audit Report

**Generated:** {timestamp}
**Analyzer:** AudioGuard v1.0 ({analyzer})

---

## {badge} Classification: `{label}`

| Field | Value |
|:---|:---|
| **File** | `{filename}` |
| **Deepfake Score** | `{score} / 100` |
| **Confidence** | `{confidence}%` |
| **Duration** | `{duration}s` |
| **Sample Rate** | `{sample_rate} Hz` |

---

## 🔍 Acoustic Feature Analysis

| Feature | Value |
|:---|:---|
{feature_rows}

---

## 📋 Recommended Action

{action}

---

## ℹ️ Score Legend

| Score Range | Confidence | Classification |
|:---|:---|:---|
| 0 – 40 | Any | 🟢 AUTHENTIC |
| 41 – 69 | ≥ 60% | 🟡 UNCERTAIN |
| 70 – 100 | ≥ 60% | 🔴 DEEPFAKE |
| Any | < 60% | 🟡 UNCERTAIN (low confidence override) |

---

*Report generated by [AudioGuard Agent](https://github.com/Srv99x/audioguard-agent) — GitAgent Hackathon 2025*
"""

    # Create reports directory and write file
    os.makedirs(output_dir, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_md)

    result = {
        "status": "success",
        "report_path": report_path,
        "classification": label,
        "badge": badge,
        "action": action
    }
    print(json.dumps(result))
    return report_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AudioGuard report generator")
    parser.add_argument("--analysis", required=True, help="JSON string from analyze.py output")
    parser.add_argument("--output-dir", default="reports", help="Directory to save report (default: reports/)")
    args = parser.parse_args()
    generate_report(args.analysis, args.output_dir)
